In [2]:
import numpy as np
from math import sqrt
import warnings
import pandas as pd
import random
from sklearn import preprocessing ,cross_validation,neighbors
from sklearn.preprocessing import Imputer
import pickle 



In [3]:
datafile="/Users/akash/Documents/dataset/User-info.xlsx"
User_data=pd.read_excel(datafile,sep=',',header=None,names=['UserId','HotelId','HotelName','Purpose','Type','Budget','Transport','Rating','Site','Hotel_Catagory'])
datay=User_data.drop(User_data.index[0])

In [4]:
###Change to numercal value 

def Num_Purpose(x):
    if x=="Holiday":
        return 1
    elif x=="Adventure":
        return 2
    elif x=="Honeymoon":
        return 3
    elif x=="Business":
        return 4
    
def Num_Type(x):
    if x=="Relax":
        return 1
    elif x=="Adventurous":
        return 2
    elif x=="Scenery":
        return 3
    elif x=="Business":
        return 4
    
    
def Num_Transport(x):
    if x=="Bus":
        return 1
    elif x=="Airplane":
        return 2
    elif x=="PCar":
        return 3
    elif x=="Train":
        return 4
    
def Num_Site(x):
    if x=="NEAR":
        return 1
    elif x=="FAR":
        return 2
    elif x=="BOTH":
        return 3
    

def Num_Hotel(x):
    
    if x=="A":
        
        return 5
    elif x=="B":
        return 4
    elif x=="C":
        return 3
    elif x=="D":
        return 2
        
    
datay['Num_Type']=datay['Type'].apply(Num_Type)
datay['Num_Transport']=datay['Transport'].apply(Num_Transport)
datay['Num_Purpose']=datay['Purpose'].apply(Num_Purpose)
datay['Num_Site']=datay['Site'].apply(Num_Site)
datay['Num_Catagory']=datay['Hotel_Catagory'].apply(Num_Hotel)
datay.head(1)
        

UserId HotelId          HotelName  Purpose         Type Budget Transport  \
1      1      A2  Hotel Cox's Today  Holiday  Adventurous  10000       Bus   

  Rating  Site Hotel_Catagory  Num_Type  Num_Transport  Num_Purpose  Num_Site  \
1      4  BOTH              A       2.0            1.0            1       3.0   

   Num_Catagory  
1             5

In [5]:
Budget = int(input("Please enter you Budget\n: "))
Type = raw_input("Please mention the type of traveller you are\n: ")
Purpose= raw_input ("Please mention the Purpose of your visit\n: ")
Duration=int(input("Please mention for how many days you are planning to stay\n: "))
Num_of_People= int(input("Please mention how many people you are planning to travel with\n: "))


Cost_Per_Day=int(Budget/(Num_of_People*Duration))

print Cost_Per_Day

example1=[]
example1.append(str(Budget))
example1.append(str(Type))
example1.append(str(Purpose))

print type(example1)

Please enter you Budget
: 30000
Please mention the type of traveller you are
: relax
Please mention the Purpose of your visit
: holiday
Please mention for how many days you are planning to stay
: 2
Please mention how many people you are planning to travel with
: 2
7500
<type 'list'>


In [6]:
if example1[1]=='scenary':
    example1[1]= '4'
if example1[1]=='relax':
    example1[1]= '3'
if example1[1]=='business':
    example1[1]= '2'
if example1[1]=='adventurous':
    example1[1]= '1' 

    
if example1[2]=='business':
    example1[2]= '4'
if example1[2]=='honeymoon':
    example1[2]= '3'
if example1[2]=='adventure':
    example1[2]= '2'
if example1[2]=='holiday':
    example1[2]= '1'  



example1=np.asarray(example1)

print example1



['30000' '3' '1']


In [7]:
H_data=datay.drop(['UserId','HotelId','HotelName','Purpose','Type','Site','Hotel_Catagory','Num_Transport','Num_Site'],axis=1)
H_data=H_data.drop(['Transport','Rating'],axis=1)

imr=Imputer(missing_values='NaN',strategy="most_frequent",axis=0)
imr=imr.fit(H_data)
H_data=imr.transform(H_data.values)

H_data=pd.DataFrame(H_data)
H_data.head()



0    1    2    3
0  10000.0  2.0  1.0  5.0
1   7000.0  1.0  1.0  4.0
2  10000.0  2.0  2.0  3.0
3  15000.0  3.0  1.0  4.0
4  10000.0  3.0  1.0  5.0

In [8]:
X=np.array(H_data.drop([3],1))
y=np.array(H_data[3])
X_train,X_test,y_train,y_test=cross_validation.train_test_split(X,y,test_size=0.1)
Hclf=neighbors.KNeighborsClassifier()
Hclf.fit(X_train,y_train)
accuracy=Hclf.score(X_test,y_test)
print(accuracy)
Hotel_prediction=Hclf.predict(example1)
Hotel_prediction=Hotel_prediction.tolist()
print Hotel_prediction

0.444444444444
[2.0]


//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [16]:
Site_Data=datay.drop(['HotelId','HotelName','Rating','Transport','Site'],axis=1)
Site_Data=Site_Data[['Budget','Num_Type','Num_Purpose','Num_Site']]
imr=Imputer(missing_values='NaN',strategy="most_frequent",axis=0)
imr=imr.fit(Site_Data)
Site_Data=imr.transform(Site_Data.values)
Site_Data=pd.DataFrame(Site_Data)
# Site_Data.head()
Site_Data[1]

0     2.0
1     1.0
2     2.0
3     3.0
4     3.0
5     3.0
6     1.0
7     1.0
8     1.0
9     2.0
10    1.0
11    3.0
12    1.0
13    1.0
14    2.0
15    1.0
16    2.0
17    1.0
18    3.0
19    1.0
20    3.0
21    2.0
22    2.0
23    3.0
24    2.0
25    3.0
26    3.0
27    3.0
28    2.0
29    1.0
     ... 
56    1.0
57    1.0
58    1.0
59    1.0
60    2.0
61    3.0
62    3.0
63    3.0
64    3.0
65    1.0
66    2.0
67    1.0
68    3.0
69    3.0
70    2.0
71    2.0
72    2.0
73    2.0
74    3.0
75    3.0
76    3.0
77    2.0
78    2.0
79    2.0
80    3.0
81    1.0
82    3.0
83    3.0
84    1.0
85    1.0
Name: 1, dtype: float64

In [33]:
Site_Data=datay.drop(['HotelId','HotelName','Rating','Transport','Site'],axis=1)
Site_Data=Site_Data[['Budget','Num_Type','Num_Purpose','Num_Site']]
imr=Imputer(missing_values='NaN',strategy="most_frequent",axis=0)
imr=imr.fit(Site_Data)
Site_Data=imr.transform(Site_Data.values)
Site_Data=pd.DataFrame(Site_Data)
Site_Data.head()

0    1    2    3
0  10000.0  2.0  1.0  3.0
1   7000.0  1.0  1.0  1.0
2  10000.0  2.0  2.0  3.0
3  15000.0  3.0  1.0  3.0
4  10000.0  3.0  1.0  1.0

In [41]:
###Predict the site 
X=np.array(Site_Data.drop([3],1))
y=np.array(Site_Data[3])
X_train,X_test,y_train,y_test=cross_validation.train_test_split(X,y,test_size=0.1)
Sclf=neighbors.KNeighborsClassifier()
Sclf.fit(X_train,y_train)
accuracy=Sclf.score(X_test,y_test)
print(accuracy)

Site_prediction=Sclf.predict(example1)  
Site_prediction=Site_prediction.tolist()
print Site_prediction

0.555555555556
[3.0]


//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [42]:
Transport_Data=datay.drop(['HotelId','HotelName','Rating','Site','Site'],axis=1)
Transport_Data.head(1)
Transport_Data=Transport_Data[['Budget','Num_Type','Num_Purpose','Num_Transport']]

imr=Imputer(missing_values='NaN',strategy="most_frequent",axis=0)
imr=imr.fit(Transport_Data)
Transport_Data=imr.transform(Transport_Data)
Transport_Data=pd.DataFrame(Transport_Data)
Transport_Data.head()


X=np.array(Transport_Data.drop([3],1))
y=np.array(Transport_Data[3])

X_train,X_test,y_train,y_test=cross_validation.train_test_split(X,y,test_size=0.1)

Tclf=neighbors.KNeighborsClassifier()
Tclf.fit(X_train,y_train)

accuracy=Tclf.score(X_test,y_test)
print(accuracy)
Transport_prediction=Tclf.predict(example1)
    



Transport_prediction=Transport_prediction.tolist()


print Transport_prediction



0.555555555556
[1.0]


//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [43]:
Recommended_Package=[]
Recommended_Package.append(Hotel_prediction)
Recommended_Package.append(Site_prediction)
Recommended_Package.append(Transport_prediction)

if Recommended_Package[0][0]==5:
    Recommended_Package[0][0]="Five Star"
if Recommended_Package[0][0]==4:
    Recommended_Package[0][0]="Four Star"
if Recommended_Package[0][0]==3:
    Recommended_Package[0][0]="Three Star"
if Recommended_Package[0][0]==2:
    Recommended_Package[0][0]="Two Star"

    
if Recommended_Package[1][0]==1:
    Recommended_Package[1][0]="Near"
if Recommended_Package[1][0]==2:
    Recommended_Package[1][0]="Far"
if Recommended_Package[1][0]==3:
    Recommended_Package[1][0]="Both"

    
if Recommended_Package[2][0]==1:
    Recommended_Package[2][0]= "Bus"
if Recommended_Package[2][0]==2:
    Recommended_Package[2][0]= "Airplane"
if Recommended_Package[2][0]==3:
    Recommended_Package[2][0]= "Car"
if Recommended_Package[2][0]==4:
    Recommended_Package[2][0]= "Train"


print Recommended_Package

[['Two Star'], ['Both'], ['Bus']]


In [44]:
###### Model Serialisation Marshalling 
pickle.dump(Hclf,open('Hotel_Recommendation.pkl','wb'))
pickle.dump(Tclf,open('Transport_Recommendation.pkl','wb'))
pickle.dump(Sclf,open('Site_Recommendation.pkl','wb'))


In [48]:
HPackage=pickle.load(open('Hotel_Recommendation.pkl','rb'))
TPackage=pickle.load(open('Transport_Recommendation.pkl','rb'))
SPackage=pickle.load(open('Site_Recommendation.pkl','rb'))

In [49]:
HPackage

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [50]:
HPackage.predict(example1)

//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 2.])

In [51]:
TPackage.predict(example1)

//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 1.])

In [52]:
SPackage.predict(example1)

//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 3.])